### ISSUE TITLE
Any way to obtain "window" object in wasm spawned in Web Worker such as in the case of demo?

### ISSUE THREAD

**Issue by eldenpark** [GoogleChromeLabs/wasm-bindgen-rayon#39]
So in the demo, we load `wasm-worker.js` by spawning a new Worker, which in turn patches the actual multhread-able wasm program.

I wonder how we can obtain `web_sys::Window` object inside that wasm program. I keep seeing that `web_sys::window()` returns `None`. `wasm-bindgen` repository has an [example](https://github.com/rustwasm/wasm-bindgen/blob/main/examples/wasm-in-web-worker/src/lib.rs) of running wasm-enabled program in Worker but the way they applied is a bit different from what's laid out in the demo. Can I get some ideas?

**Comment by RReverser** [comment]
Right, you can't because Web Workers don't have access to the window / document.

Instead, the idea in this setup is that you expose pure Rust as exports from Wasm, and do any UI work and window manipulation from JS instead, which should also be more efficient as it avoids extra layer and conversions between DOM -> JS -> Wasm (Rust).

Since the demo uses Comlink, another setup you could try is look into exposing some methods from the main thread (or even `window` itself) via Comlink to the worker, but if that's the route you want to take, I'm afraid it's something you'd have to look into on your own.
